# Generated by Django 3.2.17 on 2023-02-18 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Description',
            new_name='description',
        ),
    ]
